import glob
import os
import pathlib
import shutil

from wsl2 import constants


class Utils:
  """Container class for all util functions."""

  def prepare_folder_structure(self) -> bool:
    """Removes and creates new scratch directories."""
    try:
      if constants.Paths.SCRATCH_DIR.exists():
        shutil.rmtree(constants.Paths.SCRATCH_DIR)
      constants.Paths.SCRATCH_DIR.mkdir()
      constants.Paths.SCRATCH_RESULTS_DIR.mkdir()
      return True
    except Exception as e:
      print(e)  # TODO: Add logger message here
      return False

  def copy_pdb_files_to_wsl2(self, an_input_folder: pathlib.Path) -> bool:
    """Copies all pdb files from the input folder to the ligpargen_gui WSL2 scratch directory."""
    try:
      for tmp_file in glob.glob(os.path.join(str(an_input_folder), "*.pdb")):
        shutil.copy(pathlib.Path(tmp_file), constants.Paths.SCRATCH_DIR)
      return True
    except Exception as e:
      print(e)  # TODO: Add logger message here
      return False

  def filter_results(self, the_result_file_types: list) -> bool:
    """Filters the results generated by ligpargen for the requested types and copies them into the scratch/results folder."""
    try:
      for tmp_result_type in the_result_file_types:
        for tmp_file in self.loop_over_directory_with_wildcard(constants.Paths.SCRATCH_DIR, f"*.{tmp_result_type}"):
          shutil.copy(pathlib.Path(tmp_file), constants.Paths.SCRATCH_RESULTS_DIR)
      return True
    except Exception as e:
      print(e)  # TODO: Add logger message here
      return False

  def loop_over_directory_with_wildcard(self, a_path: pathlib.Path, a_wildcard: str) -> list:
    """Loops over a given directory and filters with the given wildcard."""
    return glob.glob(os.path.join(str(a_path), a_wildcard))
