import glob
import hashlib
import json
import logging
import os
import pathlib
import shutil
import subprocess

from wsl2 import constants
from wsl2 import default_logging, safeguard

logger = default_logging.setup_logger(__file__)


class Utils:
  """Container class for all util functions."""

  def prepare_folder_structure(self) -> bool:
    """Removes and creates new scratch directories."""
    try:
      if constants.Paths.SCRATCH_DIR.exists():
        shutil.rmtree(constants.Paths.SCRATCH_DIR)
      constants.Paths.SCRATCH_DIR.mkdir()
      constants.Paths.SCRATCH_RESULTS_DIR.mkdir()
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def copy_input_files_to_wsl2(self, an_input_folder: pathlib.Path) -> bool:
    """Copies all input files from the input folder to the ligpargen_gui WSL2 scratch directory.

    Args:
      an_input_folder: The folder to the input files.

    Returns:
      True if process was successful, Otherwise: False
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(an_input_folder is not None)
    safeguard.ENSURE(an_input_folder.exists())
    # </editor-fold>
    try:
      if an_input_folder.is_file():
        shutil.copy(an_input_folder, constants.Paths.SCRATCH_DIR)
      else:
        # Maybe loop over .mol files as well!
        for tmp_file in self.loop_over_directory_with_wildcard(an_input_folder, "*.pdb"):
          shutil.copy(pathlib.Path(tmp_file), constants.Paths.SCRATCH_DIR)
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def filter_results(self, the_result_file_types: list) -> bool:
    """Filters the results generated by ligpargen for the requested types and copies them into the scratch/results folder.

    Args:
      the_result_file_types: A list of the result file types.

    Returns:
      True if the process was successful, Otherwise: False
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(the_result_file_types is not None)
    safeguard.ENSURE(len(the_result_file_types) > 0)
    # </editor-fold>
    try:
      for tmp_result_type in the_result_file_types:
        for tmp_file in self.loop_over_directory_with_wildcard(constants.Paths.SCRATCH_DIR, f"*.{tmp_result_type}"):
          shutil.copy(pathlib.Path(tmp_file), constants.Paths.SCRATCH_RESULTS_DIR)
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def loop_over_directory_with_wildcard(self, a_path: pathlib.Path, a_wildcard: str) -> list:
    """Loops over a given directory and filters with the given wildcard.

    Args:
      a_path: The path to loop over.
      a_wildcard: The wildcard to use.

    Returns:
      A list containing all the files in the given directory that match the given wildcard.
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(a_path is not None)
    safeguard.ENSURE(a_path.exists())
    safeguard.ENSURE(a_wildcard is not None)
    safeguard.ENSURE(a_wildcard != "")
    # </editor-fold>
    return glob.glob(os.path.join(str(a_path), a_wildcard))

  def copy_files_to_windows(self, a_src_folder: pathlib.Path, a_dest_folder: pathlib.Path) -> bool:
    """Copies all pdb files from the input folder to the ligpargen_gui WSL2 scratch directory.

    Args:
      a_src_folder: The folder to the input files from Windows.
      a_dest_folder: The folder to the input files stored in the WSL2.

    Returns:
      True if the process was successful, Otherwise: False
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(a_src_folder is not None)
    safeguard.ENSURE(a_src_folder.exists())
    safeguard.ENSURE(a_dest_folder is not None)
    safeguard.ENSURE(a_dest_folder.exists())
    # </editor-fold>
    try:
      for tmp_file in self.loop_over_directory_with_wildcard(a_src_folder, "*.*"):
        shutil.copy(pathlib.Path(tmp_file), a_dest_folder)
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def run_shell_command(self, a_cmd: list) -> bool:
    """Runs a single shell command.

    Args:
      a_cmd: A list containing commands to run.

    Returns:
      True if the process finished without exceptions, Otherwise: False
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(a_cmd is not None)
    safeguard.ENSURE(len(a_cmd) > 0)
    # </editor-fold>
    try:
      subprocess.run(a_cmd, cwd="/home/alma_ligpargen/")
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def generate_snapshot(self, directory, snapshot_file) -> bool:
    """Generates a JSON snapshot of a directory's structure and file contents.

    This function recursively walks through a directory, capturing the relative
    path of each subdirectory and file, along with a hash of each file's content.
    The snapshot is saved in JSON format to a specified file.

    Args:
      directory (str): Path to the directory to snapshot.
      snapshot_file (str): Path to the file where the snapshot will be saved.

    Returns:
      True if the process was successful, Otherwise: False
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(directory is not None)
    safeguard.ENSURE(snapshot_file is not None)
    # </editor-fold>
    try:
      snapshot = {}
      for root, _, files in os.walk(directory):
        rel_path = os.path.relpath(root, directory)  # Get relative path from the base directory
        snapshot[rel_path] = {}

        for file in files:
          file_path = os.path.join(root, file)
          file_hash = self.hash_file(file_path)
          snapshot[rel_path][file] = file_hash

      with open(snapshot_file, 'w') as snapshot_file_handle:
        json.dump(snapshot, snapshot_file_handle, indent=2)
      default_logging.append_to_log_file(logger, f"Snapshot of {directory} saved to {snapshot_file}", logging.DEBUG)
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def hash_file(self, file_path) -> str:
    """Generates an MD5 hash of a file's contents.

    This function reads a file in chunks and computes an MD5 hash to
    uniquely identify its contents.

    Args:
      file_path (str): Path to the file to hash.

    Returns:
      str: The MD5 hash of the file content.
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(file_path is not None)
    # </editor-fold>
    try:
      hash_md5 = hashlib.md5()
      with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
          hash_md5.update(chunk)
      return hash_md5.hexdigest()
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return ""

  def compare_directory_to_snapshot(self, directory, snapshot_file) -> bool:
    """Compares a directory against a pre-generated snapshot for structure and content.

    This function checks if the specified directory has the same structure and file
    contents as the snapshot. It verifies that each file and subdirectory exists and
    that each file's contents match the recorded hash.

    Args:
      directory (str): Path to the directory to compare.
      snapshot_file (str): Path to the JSON snapshot file to compare against.

    Returns:
      bool: True if the directory matches the snapshot, False otherwise.
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(directory is not None)
    safeguard.ENSURE(snapshot_file is not None)
    # </editor-fold>
    try:
      with open(snapshot_file, 'r') as f:
        snapshot = json.load(f)

      for rel_path, files in snapshot.items():
        current_dir = os.path.join(directory, rel_path)
        # Check if each subdirectory exists in the current directory
        if not os.path.isdir(current_dir):
          default_logging.append_to_log_file(logger, f"Missing directory: {current_dir}", logging.WARNING)
          return False

        for file, expected_hash in files.items():
          file_path = os.path.join(current_dir, file)
          # Check if each file exists in the current directory
          if not os.path.isfile(file_path):
            default_logging.append_to_log_file(logger, f"Missing file: {file_path}", logging.WARNING)
            return False
          # Check if each file's contents match the expected hash
          actual_hash = self.hash_file(file_path)
          if actual_hash != expected_hash:
            default_logging.append_to_log_file(logger, f"File content mismatch: {file_path}", logging.WARNING)
            return False
      default_logging.append_to_log_file(logger, "Directory matches the snapshot.", logging.INFO)
      return True
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return False

  def windows_to_wsl_path(self, windows_path: str) -> str:
    """Convert a Windows path to a Linux-style WSL path.

    Args:
      windows_path (str): The Windows file path (e.g., "C:\\Users\\username\\file.txt").

    Returns:
      str: The Linux-style WSL path (e.g., "/mnt/c/Users/username/file.txt").
    """
    # <editor-fold desc="Checks">
    safeguard.ENSURE(windows_path is not None)
    # </editor-fold>
    try:
      linux_path = windows_path.replace("\\", "/")
      # Extract the drive letter and replace with /mnt/<drive>
      if len(linux_path) > 1 and linux_path[1] == ':':
        drive_letter = linux_path[0].lower()
        linux_path = f"/mnt/{drive_letter}{linux_path[2:]}"
      return linux_path
    except Exception as e:
      default_logging.append_to_log_file(logger, f"An error occurred: {e}", logging.ERROR)
      return ""
